#!/bin/bash

rootpapesdir="$HOME/pix/wallpaper/4chget"
[ -d "$rootpapesdir" ] || mkdir "$rootpapesdir"

echo "Welcome to 4chan web/image scrapping script"
echo "Is it wallpaper/general (wg) or anime wallpaper (w)?"
read option

# Validate user input
while [[ "$option" != "w" && "$option" != "wg" ]]; do
    read -p "Please choose a valid option w or wg: " option
done

if [[ $option == "w" ]] ; then
    parentdir="$rootpapesdir/w"
else 
    parentdir="$rootpapesdir/wg"
fi

echo "Enter folder name:"
read dir

# Validate directory name
while [[ -d "$parentdir/$dir" ]]; do
    read -rp "Directory already exists. Please enter a different name: " dir
done

mkdir -p "$parentdir/$dir"
echo "Directory '$dir' created successfully."

echo "Enter thread no.: (#######)"
read thread

case "$option" in
	"wg")
		wget -P "$parentdir/$dir" -nd -r -l 1 -H -D i.4cdn.org,is2.4chan.org -A png,jpg,jpeg -R '*s.*' https://boards.4chan.org/wg/thread/"$thread" ;;

	"w")
		wget -P "$parentdir/$dir" -nd -r -l 1 -H -D i.4cdn.org,is2.4chan.org -A png,jpg,jpeg -R '*s.*' https://boards.4channel.org/w/thread/"$thread" ;;
esac

echo "Wallpapers downloaded successfully."
