require("justsaumit.options")
require("justsaumit.keymaps")
require("justsaumit.plugins")
require("justsaumit.colorscheme")
require("justsaumit.treesitter-config")
require("justsaumit.lualine-config")
require("justsaumit.bufferline-config")
require("justsaumit.nvim-tree-config")
require("justsaumit.lastplace-config")
require("justsaumit.which-key-config")
require("justsaumit.colorizer-config")
require("justsaumit.telescope-config")
print ("while(!(succeed = try() ) );")
